## Base allowed qualifs export query v1.0

{% include 'sparql/_namespaces.sparql' %}

SELECT ?dui
      (GROUP_CONCAT(DISTINCT ?qui ; separator='~') AS ?qa)
WHERE {
  ?d rdf:type ?dtype .
  FILTER(?dtype IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag))
  ?d meshv:active ?actived .
  FILTER(?actived)
  ?d meshv:identifier ?dui .
  ?d meshv:allowableQualifier ?q .
  ?q meshv:active ?activeq .
  FILTER(?activeq)
  ?q meshv:identifier ?qui
}
GROUP BY ?dui
### LIMIT 100
