## Base allowed qualifs export query v1.1

{% include 'sparql/_namespaces.sparql' %}

SELECT ?dui
      (GROUP_CONCAT(DISTINCT ?qui ; separator='~') AS ?qa)
WHERE {
  ?d rdf:type ?dtype .
  FILTER(?dtype IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag))

  # Assume absence of meshv:active as true
  BIND(NOT EXISTS { ?d meshv:active false } AS ?active)
  FILTER(?active)

  ?d meshv:identifier ?dui .
  ?d meshv:allowableQualifier ?q .

  ##BIND(NOT EXISTS { ?q meshv:active false } AS ?activeq)
  ##FILTER(?activeq)

  ?q meshv:identifier ?qui
}
GROUP BY ?dui
#LIMIT 100
