## useInstead Descriptor-qualifs export query v1.1

{% include 'sparql/_namespaces.sparql' %}

SELECT ?dui (GROUP_CONCAT(DISTINCT ?o ; separator='|') AS ?qn)
WHERE {
  ?ddq meshv:hasDescriptor ?d .
  ?ddq meshv:active ?ddqactive .
  FILTER(?ddqactive) .
  ?d meshv:identifier ?dui .
  ?ddq meshv:useInstead ?adq .
  ?adq meshv:active ?adqactive .
  FILTER(?adqactive) .
  ?ddq meshv:hasQualifier ?q .
  ?q meshv:identifier ?qui .
  BIND( CONCAT(STR(?qui), '~', REPLACE(STR(?adq), str(mesh:), '')) AS ?o)
}
GROUP BY ?dui
