## Base export query v1.2

{% include 'sparql/_namespaces.sparql' %}

SELECT ?dui ?cui ?dtype ?den ?trx ?notrx ?active ?crt ?est ?nlm ?cas ?rn
      (GROUP_CONCAT(DISTINCT ?rnr ; separator='~') AS ?rrn)
      (GROUP_CONCAT(DISTINCT ?trns ; separator='~') AS ?trn)
      (GROUP_CONCAT(DISTINCT ?pac ; separator='~') AS ?pa)
      (GROUP_CONCAT(DISTINCT ?bd ; separator='~') AS ?btd)
      (GROUP_CONCAT(DISTINCT ?nd ; separator='~') AS ?ntd)
      (GROUP_CONCAT(DISTINCT ?rd ; separator='~') AS ?rtd)
WHERE {
  ?d rdf:type ?dtype .
  FILTER(?dtype IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag,meshv:Qualifier))
  ?d meshv:identifier ?dui .

  # Assume absence of meshv:active as true
  BIND(IF(EXISTS { ?d meshv:active false }, false, true) AS ?active) .

  ?d meshv:dateCreated ?crt .
  ?d meshv:dateEstablished ?est .
  OPTIONAL {
    ?d meshv:treeNumber ?tree .
    ?tree rdfs:label ?trns
  }
  ?d meshv:preferredConcept ?c .
  ?c meshv:identifier ?cui .
  ?c meshv:preferredTerm ?t .
  ?t meshv:prefLabel ?den .
  OPTIONAL {
    ?c mesht:preferredTerm ?tp .
    ?tp mesht:prefLabel ?trx
  }
  OPTIONAL {
    ?d meshv:broaderDescriptor ?bdx .
    ?bdx meshv:identifier ?bd
  }
  OPTIONAL {
    ?ndx meshv:broaderDescriptor ?d .
    ?ndx meshv:identifier ?nd
  }
  OPTIONAL {
    ?d meshv:broaderQualifier ?bdx .
    ?bdx meshv:identifier ?bd
  }
  OPTIONAL {
    ?ndx meshv:broaderQualifier ?d .
    ?ndx meshv:identifier ?nd
  }
  OPTIONAL {
    ?d meshv:seeAlso ?rdx .
    ?rdx meshv:identifier ?rd
  }
  OPTIONAL { ?c mesht:notTranslatable ?notrx }
  OPTIONAL { ?d meshv:nlmClassificationNumber ?nlm }
  OPTIONAL {
    ?d meshv:pharmacologicalAction ?phac .
    ?phac meshv:identifier ?pac
  }
  OPTIONAL { ?c meshv:registryNumber ?rn }
  OPTIONAL { ?c meshv:relatedRegistryNumber ?rnr }
  OPTIONAL { ?c meshv:casn1_label ?cas }
}
GROUP BY ?dui ?cui ?dtype ?den ?trx ?notrx ?active ?crt ?est ?nlm ?cas ?rn
###LIMIT 100

