PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX meshv:  <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh:   <http://id.nlm.nih.gov/mesh/>
PREFIX text:   <http://jena.apache.org/text#>
PREFIX meshx:  <http://mesh.medvik.cz/link/>
PREFIX mesht:  <http://www.medvik.cz/schema/mesh/vocab/#>

SELECT ?dui
      (GROUP_CONCAT(DISTINCT ?qui ; separator='~') AS ?qa)
WHERE {
  BIND(mesh:D005123 as ?d)
  ?d rdf:type ?dtype .
  FILTER(?dtype IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag))
  ?d meshv:active ?actived .
  FILTER(?actived)
  ?d meshv:identifier ?dui .
  ?d meshv:allowableQualifier ?q .
  ##?q meshv:active ?activeq .
  ##FILTER(?activeq)
  ?q meshv:identifier ?qui
}
GROUP BY ?dui
### LIMIT 100
