PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX meshv:  <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh:   <http://id.nlm.nih.gov/mesh/>
PREFIX text:   <http://jena.apache.org/text#>
PREFIX meshx:  <http://mesh.medvik.cz/link/>
PREFIX mesht:  <http://www.medvik.cz/schema/mesh/vocab/#>

## MeSH training export - notes query v1.0

SELECT ?cui ?label ?note
       (GROUP_CONCAT(DISTINCT ?trn ; separator='~') AS ?trns)
WHERE {
  {
    ?c meshv:note ?note .
    ?c rdf:type ?otype .
    FILTER(?otype IN(meshv:SCR_Anatomy, meshv:SCR_Disease, meshv:SCR_Chemical, meshv:SCR_Population, meshv:SCR_Protocol))
    ?c meshv:identifier ?cui .
    ?c rdfs:label ?label .
    FILTER (?cui IN ("C011536")) .
	?c meshv:preferredMappedTo ?d .
    OPTIONAL {
       ?d meshv:treeNumber ?tn .
       ?tn rdfs:label ?trn .
    }
  }
  UNION
  {
    ?c meshv:scopeNote ?note .
    ?c meshv:identifier ?cui .
    ?c rdfs:label ?label .
    FILTER (?cui IN ("M000761585")) .
	?d meshv:preferredConcept ?c .
    OPTIONAL {
       ?d meshv:treeNumber ?tn .
       ?tn rdfs:label ?trn .
    }
  }
  UNION
  {
    ?c mesht:scopeNote ?note .
    ?c meshv:identifier ?cui .
    ?c mesht:preferredTerm ?tp .
    ?tp mesht:prefLabel ?label .
    FILTER (?cui IN ("M0013309")) .
	?d meshv:preferredConcept ?c .
    OPTIONAL {
       ?d meshv:treeNumber ?tn .
       ?tn rdfs:label ?trn .
    }
  }
}
GROUP BY ?cui ?label ?note
LIMIT 100
