## Stats query - scopeNote - v1.0

{% include 'sparql/_namespaces.sparql' %}

select * {
{
## Pref Concepts - Descriptors
SELECT ?p (count(?p) as ?count)
WHERE {
  BIND(meshv:scopeNote as ?p)
  ?c ?p ?t .
  ?d meshv:preferredConcept ?c .
  ?d rdf:type ?type
  FILTER(?type IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag,meshv:Qualifier))
} GROUP BY ?p
} UNION {

## NonPref Concepts
SELECT ?p (count(?p) as ?count)
WHERE {
  BIND(meshv:scopeNoteX as ?p)
  ?c meshv:scopeNote ?t .
  ?d meshv:concept ?c .
  ?d rdf:type ?type
  FILTER(?type IN(meshv:TopicalDescriptor,meshv:GeographicalDescriptor,meshv:PublicationType,meshv:CheckTag,meshv:Qualifier))
} GROUP BY ?p
}
}
