## Stats query - custom nonPreferred Concepts nonPref terms - v1.0

{% include 'sparql/_namespaces.sparql' %}

select (COUNT(*) AS ?count) {
{
  SELECT ?tt
  WHERE {
    BIND(mesht:narrowerConcept as ?p)
    ?c ?p ?t .
    ?t mesht:term ?tt
  }
} UNION {
  SELECT ?tt
  WHERE {
    BIND(mesht:broaderConcept as ?p)
    ?c ?p ?t .
    ?t mesht:term ?tt
  }
} UNION {
  SELECT ?tt
  WHERE {
    BIND(mesht:relatedConcept as ?p)
    ?c ?p ?t .
    ?t mesht:term ?tt
  }
}
}
