PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX meshv:  <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh:   <http://id.nlm.nih.gov/mesh/>
PREFIX text:   <http://jena.apache.org/text#>
PREFIX mesht:  <http://www.medvik.cz/schema/mesh/vocab/#>
PREFIX meshcs: <http://mesh.medvik.cz/link/>


## Update annotation
## endpoint: http://localhost:3030/mesh/update
## params: DescriptorID (D...) or QualifierID (Q...) + value

DELETE WHERE { mesh:D009369 mesht:annotation ?o} ;
INSERT DATA  { mesh:D009369 mesht:annotation "value"@cs } ;
